name       : qt6-docs
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtbase-everywhere-src-6.2.1.tar.xz : 2c5f07b5c3ea27d3fc1a46686ea3fb6724f94dddf1fb007de3eb0bdb87429079
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 framework documentation
description: |
    qt6-docs provides the documentation for the whole Qt6 framework in a single package. Example code instead can be found in "demos" subpackages, e.g. "qt6-base-demos".
clang      : yes
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpq)
    - pkgconfig(libpulse)
    - pkgconfig(mariadb)
    - pkgconfig(odbc)
    - pkgconfig(sqlite3)
    - cups-devel
    - xdg-utils
setup      : |
    %cmake_ninja \
        -DQT_HOST_PATH=/usr \
        -DINSTALL_LIBDIR=%libdir% \
        -DINSTALL_BINDIR=%libdir%/qt6/bin \
        -DINSTALL_PUBLICBINDIR=usr/bin \
        -DINSTALL_LIBEXECDIR=%libdir%/qt6 \
        -DINSTALL_DOCDIR=share/doc/qt6 \
        -DINSTALL_ARCHDATADIR=%libdir%/qt6 \
        -DINSTALL_DATADIR=share/qt6 \
        -DINSTALL_INCLUDEDIR=include/qt6 \
        -DINSTALL_MKSPECSDIR=%libdir%/qt6/mkspecs \
        -DINSTALL_EXAMPLESDIR=share/doc/qt6/examples \
        -DQT_BUILD_EXAMPLES=ON \
        -DQT_FEATURE_journald=ON \
        -DQT_FEATURE_openssl_linked=ON
build      : |
    %ninja_build docs
install    : |
    DESTDIR=$installdir ninja -C solusBuildDir install_docs

    install -Dm00755 examples/examples.pro $installdir/usr/share/doc/qt6/examples/examples.pro
    cp -rn examples/* $installdir/usr/share/doc/qt6/examples
